name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Initialize fnm
            export PATH="/root/.local/share/fnm:$PATH"
            eval "$(fnm env --shell bash)"

            # Verify node and npm are available
            node -v
            npm -v

            # Install global packages if not present
            which pnpm || npm install -g pnpm
            which pm2 || npm install -g pm2

            # Deploy application
            cd /root/production-react-server
            git pull origin main
            pnpm i
            pm2 restart ecosystem.config.js
